### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by charles-cowart**
Fix error reporting in Qiita interface when there are less than five error messages.
Hotfixed this into production after Shrikant encountered this error.

### CODE REVIEW

**Comment by antgonza** [comment]
@charles-cowart, this can be closed, right?

**Comment by charles-cowart** [comment]
@antgonza It can be closed, but a new one should be issued. This code has migrated from klp.py to process_amplicon and process_metagenomics and the main branch does not show the change.

**Comment by antgonza** [comment]
I thought these were those lines: https://github.com/qiita-spots/qp-knight-lab-processing/blob/main/qp_klp/process_amplicon_job.py#L106

**Comment by charles-cowart** [comment]
> I thought these were those lines: https://github.com/qiita-spots/qp-knight-lab-processing/blob/main/qp_klp/process_amplicon_job.py#L106

No with that line as it is, choices will fail if tids is less than five elements. Moreover, I just checked and confirmed choices() can select the same element more than once. I'm going to issue a new PR that uses random.sample() instead:

result = tids if len(tids) < 6 else sample(tids, k=5)

**Comment by charles-cowart** [comment]
Closing. Superseded by https://github.com/qiita-spots/qp-knight-lab-processing/pull/46

**Pull request closed without merging**
